### PR TITLE
PE Dry Run Bug Fix - AddRecipeCommand

### LINKED ISSUE #181: [PE-D] Does not delete recipe
-------------
Labels: `severity.High` `type.FunctionalityBug`
original: harithadiv/ped#6

### LINKED ISSUE #182: [PE-D] Parsing in addrecipe name
Does not negate the 2nd /n flag when typed two /n flags 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: harithadiv/ped#5

### LINKED ISSUE #189: [PE-D] Wrong error message
Error message does not match the type of incorrect input.

Recipe list is empty but the error message says there there is an existing recipe with the same name.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: btricec/ped#3

### LINKED ISSUE #193: [PE-D] Error ingredient number after cooking
After a erraneous recipe as seen in issue #16 , changes to ingredient number will be erraneously increased as seen.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: synCKun/ped#17

### LINKED ISSUE #194: [PE-D] Recipe using ingredient with negative quantity
As seen in picture

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: synCKun/ped#16

### LINKED ISSUE #209: [PE-D] Error in cookrecipe
This error could be linked to the previous error on the `addrecipe` command.

As seen in the following picture, I add a recipe with `chicken` from the `meat` category, `chicken` from the `drink` category and `oil` from the `micellaneous` category. Initially, there are 8 pieces of `chicken`.

However, despite the input error in category, it proceeds to cook fried chicken. On top of that, 2 pieces of chicken are used up, since there is only 6 pieces of chicken left after cooking, as shown in the screenshot below.

Perhaps the category of the ingredient is not checked when adding it as an ingredient or a recipe. If so, it could be possible to omit the input of the category, unless the input of category is used somewhere which I am not aware of.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: chengTzeNing/ped#6

### LINKED ISSUE #210: [PE-D] Error in addrecipe command
In the `addrecipe` command, it accepts the request to add an ingredient, even if the category of the ingredient is not correct. An example is shown below, when I add `chicken` from the category of `drink`

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: chengTzeNing/ped#5

### LINKED ISSUE #211: [PE-D] addrecipe command error
When I do not add a comma in between the list of ingredients when adding a recipe, it does not show any error. It then proceeeds to add a recipe with only the first ingredient inputted.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: chengTzeNing/ped#4

### PR DESCRIPTION
**Pull request by alwayshuizhen**
The following has been added:
- fixed the negative addition of quantity for `addrecipe`
This closes #194 and subsequently closes #193.

- fixed the flagging of  missing `,` in command as an invalid command.
This closes #211

- multiple ghost parameters and extra (i.e. `/` and multiple `/n`)
This closes #181, closes #182 and closes #189

- cooks a recipe with the corresponding `ingredient_name` and `category`
This closes #209 and closes #210

### CODE REVIEW

File: src/main/java/seedu/kitchenhelper/parser/Parser.java [hunk 1]
```diff
@@ -134,6 +138,44 @@ public Command prepareAddRecipe(String attributes) throws KitchenHelperException
         return addCmd;
     }
 
+    /**
+     * Checker for command format for addrecipe command.
+     *
+     * @param command   The full user input without keyword.
+     * @return  true if is of valid command, otherwise false.
+     */
+    public Boolean checkAddRecipeCmdFormat(String command) {
```
Comment (yantingsanity) [inline src/main/java/seedu/kitchenhelper/parser/Parser.java:147]: Good fix for the addRecipe command with regards to the ghost parameters and missing invalid parameters!

File: src/main/java/seedu/kitchenhelper/command/CookRecipeCommand.java [hunk 2]
```diff
@@ -135,7 +135,9 @@ public Boolean checkForSufficientIngredient(ArrayList<Ingredient> ingredientList
         boolean isSufficient = true;
         for (Ingredient ingr : recipeToBeCooked.getRecipeItem()) {
             int totalCookedQty = pax * ingr.getQuantity();
-            if (getIngredientQty(ingr.getIngredientName().toLowerCase(), ingredientList) < totalCookedQty) {
+            String ingrName = ingr.getIngredientName().toLowerCase();
+            String ingrCategory = ingr.getCategoryName().toLowerCase();
+            if (getIngredientQty(ingrName, ingrCategory, ingredientList) < totalCookedQty) {
```
Comment (yantingsanity) [inline src/main/java/seedu/kitchenhelper/command/CookRecipeCommand.java:140]: Nice fix for issue #209 and #210

**Review by yantingsanity — COMMENTED** [review]
Tried and tested to see if the bugs will appear again, LGTM!
