### PR TITLE
Isabella refactor add delete list chores

### LINKED ISSUE #13: As a housewife, I can add chore to the list, so that I can remind myself of the tasks that needs to be completed.

### LINKED ISSUE #14: As a housewife, I can remove the task, so that I can delete a task that was keyed wrongly.

### PR DESCRIPTION
**Pull request by cheongisabella**

### CODE REVIEW

File: src/main/java/seedu/kitchenhelper/command/AddChoreCommand.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+import java.util.ArrayList;
+
+/**
+ * Adds a chore to the chore list.
+ */
+public class AddChoreCommand extends Command {
+
+    public static final String COMMAND_WORD = "addchore";
+    public static final String MESSAGE_SUCCESS = "You have added this chore:\n%s\nNow you have %s chore%s in the list.";
```
Comment (jinfayap) [inline src/main/java/seedu/kitchenhelper/command/AddChoreCommand.java:15]: Good job on using constant variable

**Review by jinfayap — COMMENTED** [review]
LGTM!
