### PR TITLE
Update fix for ListIngredient

### LINKED ISSUE #172: [PE-D] Unable to view index
Unable to view index in the list ingredient by CATEGORY

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: itskesin/ped#8

### LINKED ISSUE #186: [PE-D] Ouput formatting issues
Under list ingredient, the index and the name of the ingredient does not follow the format given:

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: harithadiv/ped#1

### LINKED ISSUE #213: [PE-D] listingredient function display format
For the listingredient function, on top of putting the format of display

`Format : Ingredient Index|Ingredient Name|Quantity|Price|Expiry`

and displaying this

`1|milo powder|2|1.0|20/04/2020`

perhaps 

`1: milo powder|2 pcs|$1.0|20/04/2020`

would be clearer to users

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: chengTzeNing/ped#2

### PR DESCRIPTION
**Pull request by JensonWee**
closes #186

### CODE REVIEW

**Comment by JensonWee** [comment]
Also fixes #172

**Comment by JensonWee** [comment]
closes #213

**Comment by JensonWee** [comment]
closes #202

File: src/main/java/seedu/kitchenhelper/command/ListIngredientCommand.java [hunk 1]
```diff
@@ -64,9 +65,9 @@ public String listIngredients(String category, ArrayList<Ingredient> ingredientL
                 for (int i = 0; i < ingredientList.size(); i++) {
                     Ingredient ingredientObj = ingredientList.get(i);
                     if (ingredientObj.getCategoryName().equalsIgnoreCase(category)) {
-                        result += ingredientObj.getIngredientName() + "|"
-                                + Integer.toString(ingredientObj.getQuantity()) + "|"
-                                + Double.toString(ingredientObj.getPrice()) + "|"
+                        result += "[" + (i + 1) + "] Ingredient Name : " + ingredientObj.getIngredientName() + " | "
```
Comment (yantingsanity) [inline src/main/java/seedu/kitchenhelper/command/ListIngredientCommand.java:68]: image

As seen from the image above, would it be better to remove the `Ingredient Name:` string before the actual ingredient name? 😆 It might be more user friendly, but just a suggestion!

**Review by yantingsanity — COMMENTED** [review]
LGTM, tried and test!
