### PR TITLE
PE Dry Run Bug Fix - DeleteIngredientCommand

### LINKED ISSUE #173: [PE-D] Delete error
There are two kailan listed in my vegetable section, when i delete kailan, not all kailan in the list are deleted?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: itskesin/ped#7

### LINKED ISSUE #174: [PE-D] Slight confusion because of the indexing
not sure whether it refer to the list based on categories or list based on all

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: itskesin/ped#6

### LINKED ISSUE #201: [PE-D] Deletion selection unclear
If i want to delete an item of the same name of different expiry date, and i use the command in the picture, it will just delete the amount of the first matching item it finds

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: synCKun/ped#10

### LINKED ISSUE #216: [PE-D] Unable to delete quntity of duplicate ingredients bug
When having duplicate ingredients as a result of an earlier bug, unable to delete said ingredient as a result

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dejunnn/ped#9

### PR DESCRIPTION
**Pull request by yantingsanity**
The following has been changed and the issues will be closed with respect to the changes: 
- Removal of DeleteIngredientCommand by name `\n` 

This closes #173, closes #201 and closes #216

Rationale to deletion of DeleteIngredientCommand by name:
Deletion by name is now removed from the current implementation for V2.1 but it may be implemented once again in the later versions, the reason for removal at this point of time is because we would want our users to delete the specific ingredients that they want to delete and that will be better implemented and less confusing to the user as we delete the ingredients by index.

### CODE REVIEW

File: src/main/java/seedu/kitchenhelper/command/DeleteIngredientCommand.java [hunk 1]
```diff
@@ -49,115 +49,95 @@ public DeleteIngredientCommand(Integer ingredientIndex, Integer quantity) {
...
+                //Delete the quantity of the ingredient
+                feedbackToUser = deleteQuantity(ingredientToDelete);
             }
+            Storage.saveIngredientData(ingredientsList);
+        } else {
+            feedbackToUser = COMMAND_FAILURE;
         }
-        return -1;
+        return feedbackToUser;
     }
```
Comment (alwayshuizhen) [inline src/main/java/seedu/kitchenhelper/command/DeleteIngredientCommand.java:77]: Great use of abstraction, easy to get the flow of what you're doing! 👍

File: src/main/java/seedu/kitchenhelper/parser/Parser.java [hunk 2]
```diff
@@ -377,24 +377,16 @@ private Command prepareDeleteRecipe(String parameters) throws KitchenHelperExcep
...
-                if (nameAndQuantity.length > 1) {
-                    return new DeleteIngredientCommand(Integer.parseInt(nameAndQuantity[0].trim()) - 1,
-                                                        Integer.parseInt(nameAndQuantity[1]));
-                } else {
-                    return new DeleteIngredientCommand(Integer.parseInt(nameAndQuantity[0].trim()) - 1,
-                                                null);
-                }
+            if (nameAndQuantity.length > 1) {
+                return new DeleteIngredientCommand(Integer.parseInt(nameAndQuantity[0].trim()) - 1,
+                                                    Integer.parseInt(nameAndQuantity[1]));
```
Comment (alwayshuizhen) [inline src/main/java/seedu/kitchenhelper/parser/Parser.java:386]: Reduction in deep nesting is good!

**Review by alwayshuizhen — APPROVED** [review]
LGTM 😄
