### PR TITLE
Fix leading and trailing space

### LINKED ISSUE #223: [PE-D] Additional Spaces in input bug
Does not account for spaces when detecting similar recipes. Can use trim() to rectify

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: dejunnn/ped#2

### PR DESCRIPTION
**Pull request by alwayshuizhen**
As per commit message.

This closes #223

### CODE REVIEW

File: src/main/java/seedu/kitchenhelper/object/Recipe.java [hunk 1]
```diff
@@ -118,7 +118,8 @@ public void setRecipeNameForStorage(String attributes) {
     public void setRecipeName(String attributes) throws KitchenHelperException {
         try {
             String recipeNameAndIngr = attributes.substring(attributes.indexOf("/n") + 3, attributes.indexOf("/i") - 1);
```
Comment (cheongisabella) [inline src/main/java/seedu/kitchenhelper/object/Recipe.java:120]: Just wondering, this is just recipeName right? Will the name recipeNameAndIngr be slightly misleading?

File: src/main/java/seedu/kitchenhelper/object/Recipe.java [hunk 2]
```diff
@@ -118,7 +118,8 @@ public void setRecipeNameForStorage(String attributes) {
...
-            recipeName = recipeNameAndIngr;
+            String trimmedRecipeName = recipeNameAndIngr.trim();
```
Comment (cheongisabella) [inline src/main/java/seedu/kitchenhelper/object/Recipe.java:121]: Good job trimming since we are not interested in the whitespace 👍

**Review by cheongisabella — COMMENTED** [review]
Good job:)
